# Generated by Django 4.1.7 on 2023-04-02 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255)),
                ('link', models.URLField(default='')),
                ('pdf_link', models.URLField(default='')),
                ('is_read', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('generated_date', models.DateTimeField(auto_now_add=True, verbose_name='date generated')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.subject')),
            ],
        ),
    ]
