# Generated by Django 4.1.7 on 2023-04-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='generated_date',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='link',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='pdf_link',
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paper',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='paper',
            name='short_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paper',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paper',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date updated'),
        ),
    ]
